on:
  push
jobs:
  debug:
    name: Build Debug
    runs-on: arch-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd $GITHUB_WORKSPACE
      - run: chmod --recursive +x ./Tools/
      - run: ./Tools/gtk/install-dependencies
      - run: ./Tools/Scripts/update-webkitgtk-libs
      - run: ./Tools/Scripts/build-webkit --gtk --debug --verbose
